name: Deploy Nuxt Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.3' 

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}  
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/nuxt-app
          pm2 reload ecosystem.config.js  # Assuming you have an ecosystem file for PM2
